### ISSUE TITLE
Fehler bei Speicherung einer Karte.

### ISSUE THREAD

**Issue by PeterPetrel** [random-access/FlashCardsManager#13]
Passiert, wenn ich die Frage:
Geben Sie ein Relationenkalkül für die folgende Abfrage an:
FINDE DIE WOHNORTE ALLER ANGESTELLTEN, 
  DIE PROGRAMMIERER SIND 
und die Antwort:
{(Angestellter.Wohnort) | Angestellter.Beruf = 'Programmierer'}
versuche einzugeben.
Fehler ist reproduzierbar. Liegt vermutlich am { oder am '.
Workaroundversuch mit double quotes und [ als Mengenklammer.
Exc. fliegt:
Caused by: ERROR 42X01: Syntax error: Encountered "Programmierer" at line 23, column 55.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.compile.ParserImpl.parseStatementOrSearchCondition(Unknown Source)
	at org.apache.derby.impl.sql.compile.ParserImpl.parseStatement(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepMinion(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepare(Unknown Source)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.prepareInternalStatement(Unknown Source)
	... 116 more

**Comment by PeterPetrel** [comment]
Double quotes reichen schon.

**Comment by random-access** [comment]
Hoppla... ' habe ich schon in Projekttiteln verboten, aber beim Refactoring vom kompletten Programm in den Karten erlaubt.
Damit ich das Zeichen nicht ganz verbieten muss habe ich es jetzt mal direkt im DBExchanger ersetzt durch &apos; - beim Auslesen der Karten wird es dann wieder zurückübersetzt. Oder kennst du einen besseren Ersatz für ' ? Immerhin werden jetzt alle &apos; egal in welchem Kontext in ' umgewandelt beim Auslesen...

**Comment by random-access** [comment]
fixed with #14
